export interface SupportedLanguage {
  code: string;
  nativeName: string;
  englishName: string;
  flagEmoji: string;
}

export const SUPPORTED_LANGUAGES: SupportedLanguage[] = [
  { code: 'system', nativeName: 'System Default', englishName: 'System Default', flagEmoji: '🌐' },
  { code: 'ru', nativeName: 'Русский', englishName: 'Russian', flagEmoji: '🇷🇺' },
  { code: 'en', nativeName: 'English', englishName: 'English', flagEmoji: '🇺🇸' },
  { code: 'es', nativeName: 'Español', englishName: 'Spanish', flagEmoji: '🇪🇸' },
  { code: 'fr', nativeName: 'Français', englishName: 'French', flagEmoji: '🇫🇷' },
  { code: 'de', nativeName: 'Deutsch', englishName: 'German', flagEmoji: '🇩🇪' },
  { code: 'it', nativeName: 'Italiano', englishName: 'Italian', flagEmoji: '🇮🇹' },
  { code: 'pt', nativeName: 'Português', englishName: 'Portuguese', flagEmoji: '🇵🇹' },
  { code: 'zh', nativeName: '中文 (简体)', englishName: 'Chinese', flagEmoji: '🇨🇳' },
  { code: 'ja', nativeName: '日本語', englishName: 'Japanese', flagEmoji: '🇯🇵' },
  { code: 'ko', nativeName: '한국어', englishName: 'Korean', flagEmoji: '🇰🇷' },
  { code: 'tr', nativeName: 'Türkçe', englishName: 'Turkish', flagEmoji: '🇹🇷' },
  { code: 'pl', nativeName: 'Polski', englishName: 'Polish', flagEmoji: '🇵🇱' },
  { code: 'uk', nativeName: 'Українська', englishName: 'Ukrainian', flagEmoji: '🇺🇦' },
  { code: 'ar', nativeName: 'العربية', englishName: 'Arabic', flagEmoji: '🇸🇦' },
  { code: 'hi', nativeName: 'हिन्दी', englishName: 'Hindi', flagEmoji: '🇮🇳' },
  { code: 'nl', nativeName: 'Nederlands', englishName: 'Dutch', flagEmoji: '🇳🇱' },
  { code: 'sv', nativeName: 'Svenska', englishName: 'Swedish', flagEmoji: '🇸🇪' },
  { code: 'vi', nativeName: 'Tiếng Việt', englishName: 'Vietnamese', flagEmoji: '🇻🇳' },
  { code: 'id', nativeName: 'Bahasa Indonesia', englishName: 'Indonesian', flagEmoji: '🇮🇩' },
  { code: 'cs', nativeName: 'Čeština', englishName: 'Czech', flagEmoji: '🇨🇿' },
  { code: 'el', nativeName: 'Ελληνικά', englishName: 'Greek', flagEmoji: '🇬🇷' },
  { code: 'ro', nativeName: 'Română', englishName: 'Romanian', flagEmoji: '🇷🇴' },
  { code: 'hu', nativeName: 'Magyar', englishName: 'Hungarian', flagEmoji: '🇭🇺' },
  { code: 'da', nativeName: 'Dansk', englishName: 'Danish', flagEmoji: '🇩🇰' },
  { code: 'fi', nativeName: 'Suomi', englishName: 'Finnish', flagEmoji: '🇫🇮' },
  { code: 'no', nativeName: 'Norsk', englishName: 'Norwegian', flagEmoji: '🇳🇴' },
  { code: 'he', nativeName: 'עברית', englishName: 'Hebrew', flagEmoji: '🇮🇱' },
  { code: 'fa', nativeName: 'فارسی', englishName: 'Persian', flagEmoji: '🇮🇷' },
  { code: 'bn', nativeName: 'বাংলা', englishName: 'Bengali', flagEmoji: '🇧🇩' },
  { code: 'th', nativeName: 'ไทย', englishName: 'Thai', flagEmoji: '🇹🇭' },
  { code: 'kk', nativeName: 'Қазақша', englishName: 'Kazakh', flagEmoji: '🇰🇿' },
  { code: 'be', nativeName: 'Беларуская', englishName: 'Belarusian', flagEmoji: '🇧🇾' },
  { code: 'uz', nativeName: 'Oʻzbekcha', englishName: 'Uzbek', flagEmoji: '🇺🇿' },
  { code: 'az', nativeName: 'Azərbaycan', englishName: 'Azerbaijani', flagEmoji: '🇦🇿' },
  { code: 'ka', nativeName: 'ქართული', englishName: 'Georgian', flagEmoji: '🇬🇪' },
  { code: 'hy', nativeName: 'Հայերեն', englishName: 'Armenian', flagEmoji: '🇦🇲' },
];

export function getSystemLanguageCode(): string {
  if (typeof navigator !== 'undefined' && navigator.language) {
    return navigator.language.split('-')[0].toLowerCase();
  }
  return 'ru';
}

export function resolveEffectiveLanguage(pref: string): string {
  if (pref && pref !== 'system') return pref.toLowerCase();
  const sys = getSystemLanguageCode();
  if (SUPPORTED_LANGUAGES.some(l => l.code === sys && l.code !== 'system')) {
    return sys;
  }
  return 'ru';
}

export function isRussian(lang: string): boolean {
  const eff = resolveEffectiveLanguage(lang);
  return eff === 'ru' || eff === 'be' || eff === 'uk' || eff === 'kk';
}

const ruDict: Record<string, string> = {
  create_proj_title: "Новый проект",
  proj_name_hint: "Название проекта (книга, сценарий...)",
  select_format: "Формат",
  cover_accent_color: "Цвет обложки",
  protect_pass_hint: "Пароль защиты (необязательно)",
  my_studio: "Моя Творческая Студия",
  cabinet: "Кабинет",
  progress: "Прогресс",
  settings: "Настройки",
  options: "Опции",
  new_project: "Новый проект",
  search: "Поиск",
  active: "Активные",
  projects: "Проекты",
  favorites: "Избранное",
  archive: "Архив",
  trash: "Корзина",
  folders: "Папки",
  documents: "Документы",
  create: "Создать",
  cancel: "Отмена",
  versions: "Версии",
  versions_subtitle: "Версии и Снимки",
  saved_versions: "Сохраненные версии:",
  save_snapshot: "Создать снимок",
  save_snapshot_label: "Название снимка",
  close: "Закрыть",
  find_replace: "Найти и заменить",
  prompter: "Суфлер",
  manual_save: "Сохранить",
  words: "Слов",
  chars: "Симв.",
  pages: "Стр.",
  reading_time: "Чтение",
  min: "мин",
  sys_settings: "Настройки",
  theme: "Тема оформления",
  theme_light: "Светлая",
  theme_dark: "Темная",
  theme_black: "Черная (OLED)",
  color_palette: "Цветовая палитра",
  choose_palette_desc: "Выберите акцентный тон или создайте свою персональную палитру",
  palette_studio: "Студия цветовой палитры",
  customize_palette_desc: "Настройте акцентный цвет, фон холста и стиль",
  custom_palette_active: "Пользовательская палитра активна",
  primary_accent: "Основной акцент",
  background_canvas: "Фон и холст",
  presets_gallery: "Галерея тем",
  saved_palettes: "Мои палитры",
  apply_palette: "Применить",
  palette_applied: "Палитра успешно применена!",
  save_as_new: "Сохранить тему",
  enter_palette_name: "Название темы",
  reset_palette: "Сбросить тему",
  hue: "Оттенок (Hue)",
  saturation: "Насыщенность (Saturation)",
  brightness: "Яркость (Brightness)",
  hex_code: "HEX-код цвета",
  quick_swatches: "Быстрые образцы",
  custom_bg_option: "Свой цвет фона холста",
  sample_book_title: "Тайна старого маяка",
  sample_chapter: "Глава 3 • 4 820 слов",
  sample_btn_action: "Продолжить писать",
  security: "Безопасность и PIN-код",
  security_sub: "Введите 4-значный пароль для блокировки Writer's Studio:",
  four_digits: "4 цифры",
  set: "Задать",
  disable_pin: "Отключить PIN-код",
  backups: "Резервные копии",
  export_backup: "Экспорт бэкапа",
  import_backup: "Импорт бэкапа",
  app_language: "Язык интерфейса",
  choose_lang_title: "Выберите язык",
  search_language: "Поиск языка...",
  lang_system: "Системный по умолчанию",
  lang_ru: "Русский",
  lang_en: "English",
  lang_es: "Español",
  interface_style: "Стиль интерфейса",
  style_pixel: "Pixel Style",
  style_classic: "Classic Style",
  bottom_bar_style: "Стиль нижней панели навигации",
  choose_bottom_bar_desc: "Выберите дизайн оформления нижней панели переключения",
  bar_standard: "Стандартная",
  bar_capsule: "Капсула (плавающая)",
  bar_segmented: "Раздельные капсулы",
  screen_refresh_rate: "Частота обновления экрана",
  choose_refresh_rate_desc: "Фиксируйте 60, 90, 120 Гц или выберите Автоматически (120 Гц плавность)",
  refresh_rate_auto: "Автоматически",
  choose_lang_desc: "Выберите язык приложения",
  choose_theme_desc: "Выберите подходящую тему",
  choose_style_desc: "Выберите внешний вид интерфейса",
  security_sub_desc: "Защитите Writer's Studio 4-значным PIN-кодом",
  backups_desc: "Экспорт и импорт локального JSON архива базы данных",
  editor_pro: "Pro режим (Блочный)",
  editor_basic: "Базовый режим (Текст)",
  create_item: "Создать запись",
  enter_title: "Введите название",
  create_folder_title: "Создать папку",
  folder_name: "Имя папки",
  create_doc_title: "Создать документ",
  doc_name: "Название документа",
  unnamed: "Без названия",
  delete: "Удалить",
  edit: "Редактировать",
  empty_text: "Введите текст...",
  stats_title: "Статистика писателя",
  stats_streak: "Серия писательства (дней):",
  stats_words: "Всего написано слов:",
  stats_chars: "Всего символов:",
  stats_daily: "Дневная продуктивность",
  select_editor_mode: "Тип редактора:",
  type_doc: "Блочный документ (Pro)",
  type_txt: "Текстовый файл (Basic)",
  format_bold: "Жирный",
  format_italic: "Курсив",
  format_underline: "Подчеркнутый",
  project_docs: "Документы проекта",
  project_root: "Корень проекта",
  create_work_hint: "Создайте папку или документ для начала работы",
  search_filter: "Поиск и фильтры",
  sort_by: "Сортировка: ",
  sort_changed: "Изм.",
  sort_name: "Имя",
  sort_created: "Созд.",
  category: "Категория: ",
  search_placeholder: "Введите название...",
  cat_all: "Все",
  cat_book: "Книга",
  cat_screenplay: "Сценарий",
  cat_story: "Рассказ",
  cat_text: "Текст",
  modified: "Изм.",
  restore: "Восстановить",
  delete_permanent: "Удалить навсегда",
  to_trash: "В корзину",
  new_project_dialog_title: "Новый литературный проект",
  project_name_label: "Название проекта (книга, сценарий...)",
  project_title_hint: "Название проекта",
  project_name_placeholder_new: "Название проекта (книга, сценарий...)",
  color_indicator: "Цветовой индикатор",
  access_password_optional: "Пароль доступа (опционально)",
  enter_password: "Ввести пароль",
  password_hint_desc: "Оставьте пустым для свободного доступа.",
  project_type: "Тип проекта:",
  color_marker: "Цветовой маркер:",
  no_projects_in_section: "Нет проектов в этом разделе",
  protected_project: "Защищенный проект",
  project_locked_hint: "Проект защищен паролем. Пожалуйста, введите пароль:",
  password: "Пароль",
  enter_btn: "Войти",
  project_folder: "Папка проекта",
  document: "Документ",
  speech_live: "Речь вслух: ~",
  minutes_left: " минут осталось",
  mirror_h: "Зеркало H",
  mirror_v: "Зеркало V",
  speed: "Скорость",
  prompter_theme: "Тема:",
  theme_dark_prompter: "Темная",
  theme_amber_prompter: "Янтарная",
  theme_bright_prompter: "Светлая",
  exit: "Выход",
  basic_mode_desc: "Базовый режим — классический текстовый редактор. Весь текст в едином поле.",
  pro_mode_desc: "Pro режим — профессиональный сценарий и книга с блоками: Сцена, Действие, Персонаж, Диалог, Кастом.",
  days_short: "дн.",
  words_suffix: "слов",
  chars_suffix: "симв.",
  productivity_title: "Продуктивность (Последние дни):",
  earlier: "Ранее",
  today: "Сегодня",
  backup_success: "Бэкап успешно восстановлен!",
  backup_error: "Ошибка восстановления бэкапа",
  read_error: "Ошибка чтения файла",
  pin_saved: "PIN-код сохранен",
  pin_removed: "PIN-код отключен",
  export_error: "Ошибка экспорта бэкапа",
  keyboard_cyrillic: "Экранная клавиатура",
  no_projects_yet: "Пока нет проектов",
  create_first_project_desc: "Создайте ваш первый проект, чтобы начать писать и воплощать замыслы.",
  keep_import_title: "Импорт из Google Keep",
  keep_import_desc: "Импорт заметок, списков и меток из Google Keep (Google Takeout ZIP, JSON, HTML, TXT)",
  keep_select_files: "Выбрать Takeout / ZIP",
  keep_paste_text: "Вставить текст",
  keep_import_dialog_title: "Импорт заметок Google Keep",
  keep_target_project_desc: "Выберите проект для сохранения заметок Google Keep:",
  keep_create_new_proj: "Создать новый проект",
  keep_project_name_placeholder: "Название проекта",
  keep_or_existing_proj: "Или добавить в существующий проект:",
  keep_importing: "Импорт заметок...",
  keep_paste_dialog_title: "Вставить заметки Google Keep",
  keep_paste_dialog_desc: "Вставьте скопированный текст или JSON заметок Google Keep:",
  keep_paste_placeholder: "Вставьте текст сюда...",
  import: "Импортировать",
  next: "Далее",
  undo: "Отменить",
  redo: "Повторить",
  take_snapshot: "Сделать снимок",
  saved_revisions: "Сохраненные ревизии:"
};

const enDict: Record<string, string> = {
  create_proj_title: "New Project",
  proj_name_hint: "Project title (book, screenplay...)",
  select_format: "Format",
  cover_accent_color: "Cover accent color",
  protect_pass_hint: "Protection password (optional)",
  my_studio: "My Creative Studio",
  cabinet: "Cabinet",
  progress: "Progress",
  settings: "Settings",
  options: "Options",
  new_project: "New Project",
  search: "Search",
  active: "Active",
  projects: "Projects",
  favorites: "Favorites",
  archive: "Archive",
  trash: "Trash",
  folders: "Folders",
  documents: "Documents",
  create: "Create",
  cancel: "Cancel",
  versions: "Versions",
  versions_subtitle: "Versions & Snapshots",
  saved_versions: "Saved revisions:",
  save_snapshot: "Create snapshot",
  save_snapshot_label: "Snapshot label",
  close: "Close",
  find_replace: "Find & Replace",
  prompter: "Prompter",
  manual_save: "Save",
  words: "Words",
  chars: "Chars",
  pages: "Pages",
  reading_time: "Reading",
  min: "min",
  sys_settings: "Settings",
  theme: "App theme",
  theme_light: "Light",
  theme_dark: "Dark",
  theme_black: "Black (OLED)",
  color_palette: "Color palette",
  choose_palette_desc: "Choose a preset accent color or craft your own unique palette",
  palette_studio: "Color Palette Studio",
  customize_palette_desc: "Customize your accent color, canvas tone, and style",
  custom_palette_active: "Custom palette in use",
  primary_accent: "Primary Accent",
  background_canvas: "Background & Canvas",
  presets_gallery: "Preset Themes",
  saved_palettes: "My Palettes",
  apply_palette: "Apply",
  palette_applied: "Palette applied successfully!",
  save_as_new: "Save Theme",
  enter_palette_name: "Theme Name",
  reset_palette: "Reset Theme",
  hue: "Hue",
  saturation: "Saturation",
  brightness: "Brightness",
  hex_code: "HEX Color Code",
  quick_swatches: "Quick Swatches",
  custom_bg_option: "Custom Background Color",
  sample_book_title: "Secret of the Lighthouse",
  sample_chapter: "Chapter 3 • 4,820 words",
  sample_btn_action: "Continue Writing",
  security: "Security and PIN protection",
  security_sub: "Enter 4-digit password to lock Writer's Studio:",
  four_digits: "4 digits",
  set: "Set",
  disable_pin: "Disable PIN Protection",
  backups: "Backup and Restore",
  export_backup: "Export Backup",
  import_backup: "Import Backup",
  app_language: "Interface language",
  choose_lang_title: "Select Language",
  search_language: "Search language...",
  lang_system: "System Default",
  lang_ru: "Russian",
  lang_en: "English",
  lang_es: "Spanish",
  interface_style: "Interface style",
  style_pixel: "Pixel Style",
  style_classic: "Classic Style",
  bottom_bar_style: "Bottom navigation bar style",
  choose_bottom_bar_desc: "Choose the visual design of the bottom navigation bar",
  bar_standard: "Standard",
  bar_capsule: "Capsule",
  bar_segmented: "Segmented capsules",
  screen_refresh_rate: "Screen refresh rate",
  choose_refresh_rate_desc: "Force display refresh rate between 60, 90, or 120 Hz, or select Automatic (120 Hz smooth animations)",
  refresh_rate_auto: "Automatic",
  choose_lang_desc: "Choose the app language",
  choose_theme_desc: "Select your preferred theme",
  choose_style_desc: "Choose the look of the interface",
  security_sub_desc: "Protect Writer's Studio with a 4-digit PIN",
  backups_desc: "Export or import local JSON backup files",
  editor_pro: "Pro Mode (Block-based)",
  editor_basic: "Basic Mode (Plain Text)",
  create_item: "Create new record",
  enter_title: "Enter title",
  create_folder_title: "Create Folder",
  folder_name: "Folder name",
  create_doc_title: "Create Document",
  doc_name: "Document name",
  unnamed: "Unnamed",
  delete: "Delete",
  edit: "Edit",
  empty_text: "Type text here...",
  stats_title: "Writer's Statistics",
  stats_streak: "Writing Streak (days):",
  stats_words: "Total Words Written:",
  stats_chars: "Total Characters Written:",
  stats_daily: "Daily Productivity Log",
  select_editor_mode: "Editor Type:",
  type_doc: "Rich Block Document (Pro)",
  type_txt: "Simple Text File (Basic)",
  format_bold: "Bold",
  format_italic: "Italic",
  format_underline: "Underline",
  project_docs: "Project Documents",
  project_root: "Project root",
  create_work_hint: "Create a folder or document to start writing",
  search_filter: "Search & Filters",
  sort_by: "Sort by: ",
  sort_changed: "Mod.",
  sort_name: "Name",
  sort_created: "Crd.",
  category: "Category: ",
  search_placeholder: "Enter name...",
  cat_all: "All",
  cat_book: "Book",
  cat_screenplay: "Screenplay",
  cat_story: "Story",
  cat_text: "Text",
  modified: "Modified",
  restore: "Restore",
  delete_permanent: "Delete permanently",
  to_trash: "Move to trash",
  new_project_dialog_title: "New Literary Project",
  project_name_label: "Project title (book, screenplay...)",
  project_title_hint: "Project title",
  project_name_placeholder_new: "Project title (book, screenplay...)",
  color_indicator: "Color indicator",
  access_password_optional: "Access password (optional)",
  enter_password: "Enter password",
  password_hint_desc: "Leave empty to keep the project private.",
  project_type: "Project type:",
  color_marker: "Color indicator:",
  no_projects_in_section: "No projects in this section",
  protected_project: "Protected Project",
  project_locked_hint: "This project is password protected. Please enter password:",
  password: "Password",
  enter_btn: "Enter",
  project_folder: "Project folder",
  document: "Document",
  speech_live: "Live speech: ~",
  minutes_left: " minutes remaining",
  mirror_h: "Mirror H",
  mirror_v: "Mirror V",
  speed: "Speed",
  prompter_theme: "Theme:",
  theme_dark_prompter: "Dark",
  theme_amber_prompter: "Amber",
  theme_bright_prompter: "Bright",
  exit: "Exit",
  basic_mode_desc: "Basic mode — standard plain text editing. The entire document is managed in a single text field.",
  pro_mode_desc: "Pro mode — structured screenplay format with Scene, Action, Character, Dialogue, and Custom blocks.",
  days_short: "days",
  words_suffix: "words",
  chars_suffix: "chars",
  productivity_title: "Productivity (Last days):",
  earlier: "Earlier",
  today: "Today",
  backup_success: "Backup successfully restored!",
  backup_error: "Error restoring backup",
  read_error: "Error reading file",
  pin_saved: "PIN configured",
  pin_removed: "PIN disabled",
  export_error: "Error exporting backup",
  keyboard_cyrillic: "On-Screen Cyrillic Input",
  no_projects_yet: "No projects yet",
  create_first_project_desc: "Create your first project to start writing and bring your ideas to life.",
  keep_import_title: "Import from Google Keep",
  keep_import_desc: "Import notes, checklists, and labels from Google Keep (Google Takeout ZIP, JSON, HTML, TXT)",
  keep_select_files: "Select Takeout / ZIP files",
  keep_paste_text: "Paste notes text",
  keep_import_dialog_title: "Import from Google Keep",
  keep_target_project_desc: "Select destination project for imported Google Keep notes:",
  keep_create_new_proj: "Create a new project",
  keep_project_name_placeholder: "Project title",
  keep_or_existing_proj: "Or select an existing project:",
  keep_importing: "Importing notes...",
  keep_paste_dialog_title: "Paste Google Keep notes",
  keep_paste_dialog_desc: "Paste text of notes or copied JSON from Google Keep:",
  keep_paste_placeholder: "Paste notes text here...",
  import: "Import",
  next: "Next",
  undo: "Undo",
  redo: "Redo",
  take_snapshot: "Take snapshot",
  saved_revisions: "Saved revisions:"
};

export function l(key: string, lang: string): string {
  const eff = resolveEffectiveLanguage(lang);
  if (eff === 'ru' || eff === 'uk' || eff === 'be' || eff === 'kk') {
    if (ruDict[key]) return ruDict[key];
  }
  if (enDict[key]) return enDict[key];
  if (ruDict[key]) return ruDict[key];
  return key.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
}
